### ISSUE TITLE
Add information about licensing

### ISSUE THREAD

**Issue by vbauer** [ColdSauce/CosmosBrowserAndroid#16]

**Comment by ColdSauce** [comment]
Hey Vladislav, thanks for opening up this issue.

We are currently working on implementing Cosmos Browser Android with a P2P protocol. We are deprecating this project and moving forward in a new repo. The new P2P product is currently a private repo because it's not at a state in which we feel it's ready to be public but we will create a public repo once we get an early version of it working. Please stay tuned for this. I will let you know personally when we are ready :)
